import { useForm, usePage } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import { Errors } from '@/Components/Field';
import type { Shared } from '@/types';

type Promo = { id: number; nama: string; tipe: 'persen' | 'nominal'; nilai: number; minimal_total: number | null; mulai: string; selesai: string; semua_cabang: number | boolean; is_active: number | boolean; branch_ids: number[] };
const blank = { nama: '', tipe: 'persen', nilai: '10', minimal_total: '', mulai: '', selesai: '', semua_cabang: true, is_active: true, branch_ids: [] as number[] };
export default function Promos({ promos, branches }: { promos: Promo[]; branches: { id: number; nama: string }[] }) {
  const writable = usePage<Shared>().props.business?.writable ?? true;
  const [editing, setEditing] = useState<number | null>(null);
  const form = useForm(blank);
  function select(promo?: Promo) { setEditing(promo?.id ?? null); form.setData(promo ? { nama: promo.nama, tipe: promo.tipe, nilai: String(promo.nilai), minimal_total: String(promo.minimal_total ?? ''), mulai: promo.mulai.slice(0, 10), selesai: promo.selesai.slice(0, 10), semua_cabang: Boolean(promo.semua_cabang), is_active: Boolean(promo.is_active), branch_ids: promo.branch_ids } : blank); form.clearErrors(); }
  function submit(event: FormEvent) { event.preventDefault(); const data = { ...form.data, nilai: Number(form.data.nilai), minimal_total: form.data.minimal_total === '' ? null : Number(form.data.minimal_total) }; form.transform(() => data); if (editing) form.put(`/owner/promos/${editing}`, { onSuccess: () => select() }); else form.post('/owner/promos', { onSuccess: () => select() }); }
  return <AppLayout title="Promo" subtitle="Atur diskon dan cabang yang boleh menggunakannya."><section className="panel"><div className="section-heading"><h2>Daftar promo</h2><button className="button button-primary" disabled={!writable} onClick={() => select()}>Buat promo</button></div>{promos.length === 0 ? <p>Belum ada promo.</p> : promos.map(promo => <div className="ops-row" key={promo.id}><strong>{promo.nama}</strong><span>{promo.tipe === 'persen' ? `${promo.nilai}%` : `Rp${promo.nilai.toLocaleString('id-ID')}`}</span><span>{promo.mulai.slice(0, 10)}–{promo.selesai.slice(0, 10)}</span><span>{promo.is_active ? 'Aktif' : 'Nonaktif'}</span><button className="button button-outline" disabled={!writable} onClick={() => select(promo)}>Ubah</button></div>)}</section>
    <section className="panel ops-form"><h2>{editing ? 'Ubah promo' : 'Promo baru'}</h2><Errors errors={form.errors} /><form onSubmit={submit}><label className="field"><span>Nama</span><input required maxLength={100} value={form.data.nama} onChange={e => form.setData('nama', e.target.value)} /></label><label className="field"><span>Tipe</span><select value={form.data.tipe} onChange={e => form.setData('tipe', e.target.value)}><option value="persen">Persen</option><option value="nominal">Nominal</option></select></label><label className="field"><span>Nilai</span><input required type="number" min="1" max={form.data.tipe === 'persen' ? 100 : 4294967295} value={form.data.nilai} onChange={e => form.setData('nilai', e.target.value)} /></label><label className="field"><span>Minimal total setelah potongan stempel (opsional)</span><input type="number" min="0" value={form.data.minimal_total} onChange={e => form.setData('minimal_total', e.target.value)} /></label><div className="ops-grid"><label className="field"><span>Mulai (WIB)</span><input required type="date" value={form.data.mulai} onChange={e => form.setData('mulai', e.target.value)} /></label><label className="field"><span>Selesai (WIB)</span><input required type="date" value={form.data.selesai} onChange={e => form.setData('selesai', e.target.value)} /></label></div><label className="checkbox-field"><input type="checkbox" checked={form.data.semua_cabang} onChange={e => form.setData('semua_cabang', e.target.checked)} /><span>Berlaku di semua cabang</span></label>{!form.data.semua_cabang && branches.map(branch => <label className="checkbox-field" key={branch.id}><input type="checkbox" checked={form.data.branch_ids.includes(branch.id)} onChange={e => form.setData('branch_ids', e.target.checked ? [...form.data.branch_ids, branch.id] : form.data.branch_ids.filter(id => id !== branch.id))} /><span>{branch.nama}</span></label>)}<label className="checkbox-field"><input type="checkbox" checked={form.data.is_active} onChange={e => form.setData('is_active', e.target.checked)} /><span>Promo aktif</span></label><button className="button button-primary" disabled={!writable || form.processing}>Simpan promo</button></form></section>
  </AppLayout>;
}
