import { useForm, router, usePage } from '@inertiajs/react';
import { RefreshCw, ArrowRight } from 'lucide-react';
import AppLayout from '@/Layouts/AppLayout';
import { Button } from '@/Components/ui/button';
import { Errors } from '@/Components/Field';
import { rupiah } from '@/lib/utils';
import type { Shared } from '@/types';
type Change = { nama: string; action: string; after: { harga: number; satuan: string; durasi_jam: number; berat_minimum: string | null }; before: { harga: number } | null };
type Preview = { fingerprint: string; branches: { id: number; nama: string; changes: Change[]; untouched: string[] }[] };
export default function Sync({ branches, preview }: { branches: { id: number; nama: string }[]; preview: Preview | null }) {
  const form = useForm<{ branches: number[] }>({ branches: preview?.branches.map(b => b.id) ?? [] });
  const writable = usePage<Shared>().props.business?.writable ?? false;
  return <AppLayout title="Sebarkan layanan" subtitle="Periksa perubahan lebih dulu. Simpan ke semua cabang pilihan sekaligus.">
    <div className="sync-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">LANGKAH 01</p><h2>Pilih cabang</h2><p>Hanya cabang aktif yang ditampilkan.</p></div></div><form className="padded" onSubmit={e => { e.preventDefault(); form.post('/owner/sync/preview', { preserveScroll: true }); }}><Errors errors={form.errors} />{branches.length === 0 && <p>Tambahkan cabang aktif terlebih dahulu.</p>}{branches.map(branch => <label className="branch-choice" key={branch.id}><input type="checkbox" checked={form.data.branches.includes(branch.id)} onChange={e => form.setData('branches', e.target.checked ? [...form.data.branches, branch.id] : form.data.branches.filter(id => id !== branch.id))} /><span>{branch.nama}</span></label>)}<Button disabled={!writable || form.processing || form.data.branches.length === 0} className="full-width">Lihat pratinjau <ArrowRight size={17} /></Button></form></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">LANGKAH 02</p><h2>Periksa & konfirmasi</h2><p>Master aktif disalin berdasarkan nama layanan.</p></div></div>{!preview ? <div className="empty-state"><RefreshCw size={38} strokeWidth={1.3} /><h3>Pratinjau Anda akan tampil di sini</h3><p>Pilih cabang tujuan lalu tekan Lihat pratinjau.</p></div> : <div className="padded"><div className="notice">Nama yang sama diperbarui, layanan lokal nonaktif diaktifkan kembali, dan layanan khusus lainnya tetap.</div>{preview.branches.map(branch => <div className="preview-branch" key={branch.id}><h3>{branch.nama}</h3><p className="muted">{branch.changes.filter(c => c.action === 'tambah').length} ditambahkan · {branch.changes.filter(c => c.action === 'perbarui').length} diperbarui · {branch.changes.filter(c => c.action === 'aktifkan').length} diaktifkan kembali</p>{branch.changes.map(change => <div className="preview-change" key={change.nama}><div><strong>{change.nama}</strong><small>{change.before ? `${rupiah(change.before.harga)} → ` : ''}{rupiah(change.after.harga)} / {change.after.satuan} · {change.after.durasi_jam} jam{change.after.berat_minimum ? ` · min ${change.after.berat_minimum} kg` : ''}</small></div><span className="pill">{change.action === 'tambah' ? 'Baru' : change.action === 'aktifkan' ? 'Aktif kembali' : 'Perbarui'}</span></div>)}{branch.untouched.length > 0 && <p className="form-hint">Tidak diubah: {branch.untouched.join(', ')}</p>}</div>)}<Button className="full-width" disabled={!writable} onClick={() => { if (window.confirm(`Terapkan perubahan ke ${preview.branches.length} cabang sesuai pratinjau?`)) router.post('/owner/sync', { branches: preview.branches.map(b => b.id), fingerprint: preview.fingerprint, confirmed: true }); }}>Konfirmasi & terapkan</Button></div>}</section></div>
  </AppLayout>;
}
