import { Link, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { rupiah } from '@/lib/utils';

type Row = { id: number; kode_resi: string; status: string; status_bayar?: string; total_akhir?: number; waktu_masuk?: string; estimasi_selesai?: string; umur_hari?: number };
type Summary = { today: Row[]; counts: Record<string, number>; ready: Row[]; late: Row[]; today_count: number; today_kg: string };
export default function AdminHome({ branches, branchId, branchName, summary }: { branches: { id: number; nama: string }[]; branchId: number; branchName: string | null; summary: Summary | null }) {
  return <AppLayout title="Operasional cabang" subtitle={`${branchName ?? 'Cabang'} · Lihat pekerjaan masuk, terlambat, dan siap diambil.`} action={<Link className="button button-primary" href={`/app/transactions/create?branch_id=${branchId}`}>Transaksi baru</Link>}>
    {branches.length > 0 && <label className="field"><span>Pilih cabang</span><select value={branchId} onChange={event => router.get('/app', { branch_id: event.target.value })}>{branches.map(branch => <option key={branch.id} value={branch.id}>{branch.nama}</option>)}</select></label>}
    {!summary ? <p className="notice">Belum ada cabang. Buat cabang dan layanan terlebih dahulu.</p> : <>
      <div className="stats-grid"><div className="stat-card"><strong className="stat-number">{summary.today_count}</strong><span>Transaksi masuk hari ini</span></div><div className="stat-card"><strong className="stat-number">{String(summary.today_kg).replace('.', ',')} kg</strong><span>Berat aktual hari ini</span></div><div className="stat-card"><strong className="stat-number">{summary.counts.DITERIMA ?? 0}</strong><span>Diterima</span></div><div className="stat-card"><strong className="stat-number">{summary.counts.DIPROSES ?? 0}</strong><span>Diproses</span></div><div className="stat-card"><strong className="stat-number">{summary.counts.SIAP_DIAMBIL ?? 0}</strong><span>Siap diambil</span></div></div>
      <section className="panel"><div className="section-heading"><h2>Siap diambil — belum diambil</h2></div>{summary.ready.length === 0 ? <p className="ops-empty">Belum ada cucian siap diambil.</p> : summary.ready.map(row => <Link className="ops-row" href={`/app/transactions/${row.id}`} key={row.id}><strong>{row.kode_resi}</strong><span>{row.umur_hari} hari menunggu</span><span>{row.status_bayar}</span></Link>)}</section>
      <section className="panel"><div className="section-heading"><h2>Terlambat</h2></div>{summary.late.length === 0 ? <p className="ops-empty">Tidak ada cucian terlambat.</p> : summary.late.map(row => <Link className="ops-row" href={`/app/transactions/${row.id}`} key={row.id}><strong>{row.kode_resi}</strong><span>{row.status.replaceAll('_', ' ')}</span><span>{row.estimasi_selesai} WIB</span></Link>)}</section>
      <section className="panel"><div className="section-heading"><h2>Transaksi hari ini</h2><Link className="button button-outline" href="/app/transactions">Cari transaksi</Link></div>{summary.today.length === 0 ? <p className="ops-empty">Belum ada transaksi hari ini.</p> : summary.today.map(row => <Link className="ops-row" href={`/app/transactions/${row.id}`} key={row.id}><strong>{row.kode_resi}</strong><span>{row.status.replaceAll('_', ' ')}</span><span>{rupiah(row.total_akhir ?? 0)}</span></Link>)}</section>
    </>}
    <div className="ops-actions"><Link className="button button-outline" href="/app/customers">Kelola pelanggan</Link><Link className="button button-outline" href="/app/transactions">Cari transaksi</Link></div>
  </AppLayout>;
}
