import { Link, usePage } from '@inertiajs/react';
import { ArrowUpRight, Store, Users, Layers, CheckCircle2 } from 'lucide-react';
import AppLayout from '@/Layouts/AppLayout';
import type { Shared } from '@/types';
export default function Dashboard({ branchCount, adminCount, serviceCount }: { branchCount: number; adminCount: number; serviceCount: number }) {
  const { auth } = usePage<Shared>().props;
  return <AppLayout title={`Halo, ${auth?.nama.split(' ')[0] ?? 'Owner'}.`} subtitle="Siapkan bisnis Anda, satu langkah sederhana setiap hari.">
    <section className="hero-card"><div><span className="pill pill-light">RUANG UNTUK BERTUMBUH</span><h2>Bisnis yang rapi,<br />dimulai dari fondasi yang baik.</h2><p>Atur cabang, beri akses kepada tim, dan siapkan layanan yang pelanggan butuhkan.</p></div><div className="hero-mark"><Layers size={100} strokeWidth={1} /></div></section>
    <section className="stats-grid">{[{ count: branchCount, label: 'Cabang laundry', icon: Store, href: '/owner/branches' }, { count: adminCount, label: 'Anggota tim admin', icon: Users, href: '/owner/admins' }, { count: serviceCount, label: 'Layanan master', icon: Layers, href: '/owner/masters' }].map(({ count, label, icon: Icon, href }) => <Link href={href} className="stat-card" key={label}><span className="stat-icon"><Icon size={22} /></span><span className="stat-number">{count}</span><span>{label}</span><ArrowUpRight className="stat-arrow" size={18} /></Link>)}</section>
    <section className="panel"><div className="section-heading"><div><h2>Langkah awal bisnis Anda</h2><p>Lengkapi pengaturan sebelum memulai operasional.</p></div><span className="pill">Fondasi bisnis</span></div>{[{ href: '/owner/branches', done: branchCount > 0, title: 'Tambahkan cabang pertama', text: 'Simpan nama, alamat, dan nomor telepon laundry.' }, { href: '/owner/admins', done: adminCount > 0, title: 'Ajak tim Anda bekerja', text: 'Buat akun admin dan tentukan cabang tugasnya.' }, { href: '/owner/masters', done: serviceCount > 0, title: 'Siapkan daftar layanan', text: 'Atur harga dan durasi, kemudian sebarkan ke cabang.' }].map((item, i) => <Link className="checklist-row" href={item.href} key={item.href}><span className={item.done ? 'step done' : 'step'}>{item.done ? <CheckCircle2 size={22} /> : `0${i + 1}`}</span><span><strong>{item.title}</strong><small>{item.text}</small></span><ArrowUpRight size={19} /></Link>)}</section>
    <div className="ops-actions"><Link className="button button-primary" href="/app">Buka operasional</Link><Link className="button button-outline" href="/owner/settings/payment">Atur pembayaran dan DP</Link></div>
  </AppLayout>;
}
