import { Link, router } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import { rupiah } from '@/lib/utils';
type Service = { id: number; nama: string; satuan: 'kg' | 'item'; harga: number };
type Item = { service_id: number | null; berat_kg: string | null; jumlah_unit: number | null; perkiraan_jumlah_baju: number | null };
type Draft = { service_id: number; berat_kg: string; jumlah_unit: string; perkiraan_jumlah_baju: string };
export default function TransactionEdit({ transaction, services, items }: { transaction: { id: number; kode_resi: string; branch_id: number; version: number }; services: Service[]; items: Item[] }) {
  const [rows, setRows] = useState<Draft[]>(items.map(row => ({ service_id: row.service_id ?? services[0]?.id ?? 0, berat_kg: row.berat_kg ?? '', jumlah_unit: String(row.jumlah_unit ?? ''), perkiraan_jumlah_baju: String(row.perkiraan_jumlah_baju ?? '') })));
  const [quote, setQuote] = useState<{ fingerprint: string; total_akhir: number; items: { nama_layanan_snapshot: string; subtotal: number }[] } | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const payload = () => rows.map(row => ({ service_id: row.service_id, ...(services.find(service => service.id === row.service_id)?.satuan === 'kg' ? { berat_kg: row.berat_kg } : { jumlah_unit: row.jumlah_unit }), perkiraan_jumlah_baju: row.perkiraan_jumlah_baju || null }));
  const change = (index: number, patch: Partial<Draft>) => { setRows(old => old.map((row, i) => i === index ? { ...row, ...patch } : row)); setQuote(null); };
  async function preview(event: FormEvent) { event.preventDefault(); const response = await fetch('/app/quote', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', 'Accept': 'application/json', 'X-CSRF-TOKEN': document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content ?? '' }, body: JSON.stringify({ branch_id: transaction.branch_id, items: payload() }) }); const data = await response.json(); if (!response.ok) setErrors(data.errors ?? { quote: data.message }); else { setErrors({}); setQuote(data); } }
  return <AppLayout title={`Ubah layanan ${transaction.kode_resi}`} subtitle="Harga terbaru akan ditampilkan untuk konfirmasi sebelum disimpan." action={<Link className="button button-outline" href={`/app/transactions/${transaction.id}`}>Kembali</Link>}>
    {Object.values(errors).length > 0 && <div className="notice notice-danger">{Object.values(errors).map((error, i) => <p key={i}>{error}</p>)}</div>}
    <form onSubmit={preview}><section className="panel ops-form">{rows.map((row, index) => <div className="ops-item" key={index}><label className="field"><span>Layanan</span><select value={row.service_id} onChange={e => change(index, { service_id: Number(e.target.value), berat_kg: '', jumlah_unit: '' })}>{services.map(service => <option key={service.id} value={service.id}>{service.nama} · {rupiah(service.harga)}</option>)}</select></label>{services.find(service => service.id === row.service_id)?.satuan === 'kg' ? <label className="field"><span>Berat (kg)</span><input required type="number" min="0.1" max="9999.9" step="0.1" value={row.berat_kg} onChange={e => change(index, { berat_kg: e.target.value })} /></label> : <label className="field"><span>Jumlah item</span><input required type="number" min="1" max="65535" value={row.jumlah_unit} onChange={e => change(index, { jumlah_unit: e.target.value })} /></label>}<label className="field"><span>Perkiraan jumlah baju</span><input type="number" min="0" max="65535" value={row.perkiraan_jumlah_baju} onChange={e => change(index, { perkiraan_jumlah_baju: e.target.value })} /></label><button className="button button-outline" type="button" disabled={rows.length === 1} onClick={() => { setRows(old => old.filter((_, i) => i !== index)); setQuote(null); }}>Hapus</button></div>)}<button className="button button-outline" type="button" disabled={rows.length >= 100} onClick={() => { setRows(old => [...old, { service_id: services[0].id, berat_kg: '', jumlah_unit: '', perkiraan_jumlah_baju: '' }]); setQuote(null); }}>Tambah layanan</button><button className="button button-outline" type="submit">Hitung ulang harga</button></section></form>
    {quote && <section className="panel ops-form"><h2>Konfirmasi harga baru</h2>{quote.items.map((row, i) => <div className="ops-row" key={i}><span>{row.nama_layanan_snapshot}</span><strong>{rupiah(row.subtotal)}</strong></div>)}<div className="ops-row"><strong>Total baru</strong><strong>{rupiah(quote.total_akhir)}</strong></div><button className="button button-primary" onClick={() => router.put(`/app/transactions/${transaction.id}`, { expected_version: transaction.version, items: payload(), quote_fingerprint: quote.fingerprint }, { onError: setErrors, onSuccess: () => router.visit(`/app/transactions/${transaction.id}`) })}>Simpan harga baru</button></section>}
  </AppLayout>;
}
