import { Link, router, usePage } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import { rupiah } from '@/lib/utils';
import type { Shared } from '@/types';

type Tx = { id: number; kode_resi: string; status: string; status_bayar: string; total_akhir: number; subtotal: number; version: number; estimasi_selesai: string; catatan_kondisi: string | null; waktu_masuk: string };
type Item = { id: number; nama_layanan_snapshot: string; satuan_snapshot: string; harga_snapshot: number; berat_kg: string | null; jumlah_unit: number | null; perkiraan_jumlah_baju: number | null; subtotal: number };
type Payment = { id: number; jumlah: number; metode: string; waktu: string };
export default function TransactionDetail({ transaction: tx, customer, items, payments, history, paid, manualLink }: { transaction: Tx; customer: { nama: string; no_hp: string }; items: Item[]; payments: Payment[]; history: { status: string; created_at: string }[]; paid: number; manualLink: string }) {
  const writable = usePage<Shared>().props.business?.writable ?? true;
  const [amount, setAmount] = useState('');
  const [method, setMethod] = useState('tunai');
  const [paymentKey, setPaymentKey] = useState(() => crypto.randomUUID());
  const [reason, setReason] = useState('');
  const [condition, setCondition] = useState(tx.catatan_kondisi ?? '');
  const [estimate, setEstimate] = useState(tx.estimasi_selesai.replace(' ', 'T').slice(0, 16));
  const [clothes, setClothes] = useState<Record<number, string>>(() => Object.fromEntries(items.map(item => [item.id, item.perkiraan_jumlah_baju === null ? '' : String(item.perkiraan_jumlah_baju)])));
  const [errors, setErrors] = useState<Record<string, string>>({});
  const active = ['DITERIMA', 'DIPROSES', 'SIAP_DIAMBIL'].includes(tx.status);
  const next = tx.status === 'DITERIMA' ? 'DIPROSES' : tx.status === 'DIPROSES' ? 'SIAP_DIAMBIL' : tx.status === 'SIAP_DIAMBIL' ? 'SUDAH_DIAMBIL' : null;
  function pay(event: FormEvent) { event.preventDefault(); router.post(`/app/transactions/${tx.id}/payments`, { request_key: paymentKey, jumlah: Number(amount), metode: method }, { onError: setErrors, onSuccess: () => { setPaymentKey(crypto.randomUUID()); setAmount(''); } }); }
  function change(status: string) { if (status === 'DIBATALKAN' && !window.confirm('Batalkan transaksi ini? Pembayaran lama tetap tersimpan dan pengembalian dana ditangani di luar aplikasi.')) return; router.post(`/app/transactions/${tx.id}/status`, { status, expected_version: tx.version, ...(status === 'DIBATALKAN' ? { alasan_pembatalan: reason } : {}) }, { onError: setErrors }); }
  return <AppLayout title={`Resi ${tx.kode_resi}`} subtitle={`${customer.nama} · ${customer.no_hp}`} action={<Link className="button button-outline" href="/app/transactions">Daftar transaksi</Link>}>
    {Object.keys(errors).length > 0 && <div className="notice notice-danger" role="alert">{Object.values(errors).map((message, index) => <p key={index}>{message}</p>)}</div>}
    <div className="stats-grid"><div className="stat-card"><strong className="stat-number">{rupiah(tx.total_akhir)}</strong><span>Total akhir</span></div><div className="stat-card"><strong className="stat-number">{rupiah(paid)}</strong><span>Terbayar</span></div><div className="stat-card"><strong className="stat-number">{rupiah(Math.max(0, tx.total_akhir - paid))}</strong><span>Sisa · {tx.status_bayar}</span></div></div>
    <section className="panel ops-form"><h2>{tx.status.replaceAll('_', ' ')}</h2><p>Masuk {tx.waktu_masuk} WIB · Estimasi {tx.estimasi_selesai} WIB</p><div className="ops-actions"><a className="button button-outline" href={`/app/transactions/${tx.id}/print`} target="_blank" rel="noreferrer">Cetak resi 58 mm</a><a className="button button-outline" href={`/t/${tx.kode_resi}`} target="_blank" rel="noreferrer">Status publik</a><a className="button button-outline" href={manualLink} target="_blank" rel="noreferrer">Kirim resi via WhatsApp</a></div></section>
    <section className="panel"><div className="section-heading"><h2>Rincian layanan</h2></div>{items.map(item => <div className="ops-row" key={item.id}><strong>{item.nama_layanan_snapshot}</strong><span>{item.satuan_snapshot === 'kg' ? `${String(item.berat_kg).replace('.', ',')} kg` : `${item.jumlah_unit} item`} × {rupiah(item.harga_snapshot)}</span><strong>{rupiah(item.subtotal)}</strong></div>)}</section>
    {active && writable && <section className="panel ops-form"><h2>Pembayaran</h2>{tx.total_akhir > paid && <form onSubmit={pay}><label className="field"><span>Jumlah (Rp)</span><input type="number" min="1" max={tx.total_akhir - paid} required value={amount} onChange={e => setAmount(e.target.value)} /></label><label className="field"><span>Metode</span><select value={method} onChange={e => setMethod(e.target.value)}><option value="tunai">Tunai</option><option value="transfer">Transfer</option></select></label><button className="button button-primary">Catat pembayaran</button></form>}{payments.length > 0 && <div>{payments.map(row => <div className="ops-row" key={row.id}><span>{row.waktu} WIB · {row.metode}</span><strong>{rupiah(row.jumlah)}</strong></div>)}</div>}</section>}
    {active && writable && <section className="panel ops-form"><h2>Perbarui status</h2>{next && <button className="button button-primary" disabled={next === 'SUDAH_DIAMBIL' && tx.status_bayar !== 'LUNAS'} onClick={() => change(next)}>Pindah ke {next.replaceAll('_', ' ')}</button>}<label className="field"><span>Alasan pembatalan</span><textarea value={reason} onChange={e => setReason(e.target.value)} rows={2} /></label><button className="button button-danger" onClick={() => change('DIBATALKAN')}>Batalkan transaksi</button></section>}
    {tx.status === 'DITERIMA' && writable && <section className="panel ops-form"><h2>Ubah catatan dan estimasi</h2><form onSubmit={event => { event.preventDefault(); router.put(`/app/transactions/${tx.id}`, { expected_version: tx.version, catatan_kondisi: condition, estimasi_selesai: estimate, item_clothes: Object.fromEntries(Object.entries(clothes).map(([id, value]) => [id, value === '' ? null : Number(value)])) }, { onError: setErrors }); }}><label className="field"><span>Catatan kondisi (publik)</span><textarea rows={3} value={condition} onChange={e => setCondition(e.target.value)} /></label><label className="field"><span>Estimasi selesai</span><input type="datetime-local" value={estimate} onChange={e => setEstimate(e.target.value)} /></label>{items.map(item => <label className="field" key={item.id}><span>Perkiraan jumlah baju · {item.nama_layanan_snapshot}</span><input type="number" min="0" max="65535" value={clothes[item.id] ?? ''} onChange={event => setClothes(old => ({ ...old, [item.id]: event.target.value }))} /></label>)}<button className="button button-outline">Simpan perubahan</button></form><Link className="button button-outline" href={`/app/transactions/${tx.id}/edit`}>Ubah layanan dan harga</Link></section>}
    <section className="panel"><div className="section-heading"><h2>Riwayat status</h2></div>{history.map((row, index) => <div className="ops-row" key={index}><strong>{row.status.replaceAll('_', ' ')}</strong><span>{row.created_at} WIB</span></div>)}</section>
  </AppLayout>;
}
