import { Link, router, usePage } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import { rupiah } from '@/lib/utils';
import type { Shared } from '@/types';

type Tx = { id: number; customer_id: number; kode_resi: string; status: string; status_bayar: string; total_akhir: number; subtotal: number; potongan_stempel: number; potongan_promo: number; promo_nama_snapshot: string | null; stamp_reward_max_kg_snapshot: string | null; version: number; estimasi_selesai: string; catatan_kondisi: string | null; waktu_masuk: string };
type Item = { id: number; nama_layanan_snapshot: string; satuan_snapshot: string; harga_snapshot: number; berat_kg: string | null; jumlah_unit: number | null; perkiraan_jumlah_baju: number | null; subtotal: number };
type Payment = { id: number; jumlah: number; metode: string; waktu: string };
type Notification = { kanal: string; tipe: string; tujuan: string; status: string; reason_code: string | null; attempt_count: number; created_at: string; sent_at: string | null };
export default function TransactionDetail({ transaction: tx, customer, items, payments, history, paid, manualLink, notifications = [] }: { transaction: Tx; customer: { nama: string; no_hp: string }; items: Item[]; payments: Payment[]; history: { status: string; created_at: string }[]; paid: number; manualLink: string; notifications?: Notification[] }) {
  const writable = usePage<Shared>().props.business?.writable ?? true;
  const [amount, setAmount] = useState('');
  const [method, setMethod] = useState('tunai');
  const [paymentKey, setPaymentKey] = useState(() => crypto.randomUUID());
  const [reason, setReason] = useState('');
  const [condition, setCondition] = useState(tx.catatan_kondisi ?? '');
  const [estimate, setEstimate] = useState(tx.estimasi_selesai.replace(' ', 'T').slice(0, 16));
  const [clothes, setClothes] = useState<Record<number, string>>(() => Object.fromEntries(items.map(item => [item.id, item.perkiraan_jumlah_baju === null ? '' : String(item.perkiraan_jumlah_baju)])));
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [manualEmailKey, setManualEmailKey] = useState(() => crypto.randomUUID());
  const csrf = document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content ?? '';
  const hasUnknown = notifications.some(row => row.status === 'perlu_pemeriksaan');
  function confirmWa(event: FormEvent<HTMLFormElement>) { if (hasUnknown && !window.confirm('Hasil kiriman sebelumnya belum diketahui. Menghubungi lagi dapat menghasilkan pesan ganda. Lanjutkan?')) event.preventDefault(); }
  const active = ['DITERIMA', 'DIPROSES', 'SIAP_DIAMBIL'].includes(tx.status);
  const next = tx.status === 'DITERIMA' ? 'DIPROSES' : tx.status === 'DIPROSES' ? 'SIAP_DIAMBIL' : tx.status === 'SIAP_DIAMBIL' ? 'SUDAH_DIAMBIL' : null;
  function pay(event: FormEvent) { event.preventDefault(); router.post(`/app/transactions/${tx.id}/payments`, { request_key: paymentKey, jumlah: Number(amount), metode: method }, { onError: setErrors, onSuccess: () => { setPaymentKey(crypto.randomUUID()); setAmount(''); } }); }
  function change(status: string) { if (status === 'DIBATALKAN' && !window.confirm('Batalkan transaksi ini? Pembayaran lama tetap tersimpan dan pengembalian dana ditangani di luar aplikasi.')) return; router.post(`/app/transactions/${tx.id}/status`, { status, expected_version: tx.version, ...(status === 'DIBATALKAN' ? { alasan_pembatalan: reason } : {}) }, { onError: setErrors }); }
  return <AppLayout title={`Resi ${tx.kode_resi}`} subtitle={`${customer.nama} · ${customer.no_hp}`} action={<Link className="button button-outline" href="/app/transactions">Daftar transaksi</Link>}>
    <section className="panel ops-form"><div className="ops-row"><span>Subtotal</span><strong>{rupiah(tx.subtotal)}</strong></div>{tx.potongan_stempel > 0 && <div className="ops-row"><span>Hadiah stempel {tx.stamp_reward_max_kg_snapshot ? `· maks ${tx.stamp_reward_max_kg_snapshot} kg` : ''}</span><strong>−{rupiah(tx.potongan_stempel)}</strong></div>}{tx.potongan_promo > 0 && <div className="ops-row"><span>Promo {tx.promo_nama_snapshot}</span><strong>−{rupiah(tx.potongan_promo)}</strong></div>}<Link className="button button-outline" href={`/app/customers/${tx.customer_id}/loyalty`}>Riwayat stempel pelanggan</Link></section>
    {Object.keys(errors).length > 0 && <div className="notice notice-danger" role="alert">{Object.values(errors).map((message, index) => <p key={index}>{message}</p>)}</div>}
    <div className="stats-grid"><div className="stat-card"><strong className="stat-number">{rupiah(tx.total_akhir)}</strong><span>Total akhir</span></div><div className="stat-card"><strong className="stat-number">{rupiah(paid)}</strong><span>Terbayar</span></div><div className="stat-card"><strong className="stat-number">{rupiah(Math.max(0, tx.total_akhir - paid))}</strong><span>Sisa · {tx.status_bayar}</span></div></div>
    <section className="panel ops-form"><h2>{tx.status.replaceAll('_', ' ')}</h2><p>Masuk {tx.waktu_masuk} WIB · Estimasi {tx.estimasi_selesai} WIB</p><div className="ops-actions"><a className="button button-outline" href={`/app/transactions/${tx.id}/print`} target="_blank" rel="noreferrer">Cetak resi 58 mm</a><a className="button button-outline" href={`/t/${tx.kode_resi}`} target="_blank" rel="noreferrer">Status publik</a>{writable ? <form method="post" action={`/app/transactions/${tx.id}/notifications/whatsapp`} target="_blank" onSubmit={confirmWa}><input type="hidden" name="_token" value={csrf} /><input type="hidden" name="type" value="resi" /><input type="hidden" name="request_key" value={crypto.randomUUID()} /><input type="hidden" name="confirm_unknown" value={hasUnknown ? '1' : '0'} /><button className="button button-outline" type="submit">Buka resi via WhatsApp</button></form> : <a className="button button-outline" href={manualLink} target="_blank" rel="noreferrer" onClick={event => { if (hasUnknown && !window.confirm('Hasil kiriman sebelumnya belum diketahui. Lanjutkan?')) event.preventDefault(); }}>Buka resi via WhatsApp</a>}</div></section>
    {tx.status === 'SIAP_DIAMBIL' && writable && <section className="panel ops-form"><h2>Pengingat manual</h2><p>Pengiriman email dicatat secara terpisah dari pengingat otomatis. Bila hasil sebelumnya belum diketahui, periksa pelanggan sebelum menghubungi lagi.</p><div className="ops-actions"><button className="button button-outline" onClick={() => { const confirmed = !hasUnknown || window.confirm('Hasil kiriman sebelumnya belum diketahui. Pesan dapat terkirim dua kali. Lanjutkan?'); if (confirmed) router.post(`/app/transactions/${tx.id}/notifications/email`, { request_key: manualEmailKey, confirm_unknown: hasUnknown }, { onError: setErrors, onSuccess: () => setManualEmailKey(crypto.randomUUID()) }); }}>Kirim email pengingat</button><form method="post" action={`/app/transactions/${tx.id}/notifications/whatsapp`} target="_blank" onSubmit={confirmWa}><input type="hidden" name="_token" value={csrf} /><input type="hidden" name="type" value="pengingat" /><input type="hidden" name="request_key" value={crypto.randomUUID()} /><input type="hidden" name="confirm_unknown" value={hasUnknown ? '1' : '0'} /><button className="button button-outline" type="submit">Buka pengingat WA</button></form></div></section>}
    <section className="panel"><div className="section-heading"><h2>Rincian layanan</h2></div>{items.map(item => <div className="ops-row" key={item.id}><strong>{item.nama_layanan_snapshot}</strong><span>{item.satuan_snapshot === 'kg' ? `${String(item.berat_kg).replace('.', ',')} kg` : `${item.jumlah_unit} item`} × {rupiah(item.harga_snapshot)}</span><strong>{rupiah(item.subtotal)}</strong></div>)}</section>
    {active && writable && <section className="panel ops-form"><h2>Pembayaran</h2>{tx.total_akhir > paid && <form onSubmit={pay}><label className="field"><span>Jumlah (Rp)</span><input type="number" min="1" max={tx.total_akhir - paid} required value={amount} onChange={e => setAmount(e.target.value)} /></label><label className="field"><span>Metode</span><select value={method} onChange={e => setMethod(e.target.value)}><option value="tunai">Tunai</option><option value="transfer">Transfer</option></select></label><button className="button button-primary">Catat pembayaran</button></form>}{payments.length > 0 && <div>{payments.map(row => <div className="ops-row" key={row.id}><span>{row.waktu} WIB · {row.metode}</span><strong>{rupiah(row.jumlah)}</strong></div>)}</div>}</section>}
    {active && writable && <section className="panel ops-form"><h2>Perbarui status</h2>{next && <button className="button button-primary" disabled={next === 'SUDAH_DIAMBIL' && tx.status_bayar !== 'LUNAS'} onClick={() => change(next)}>Pindah ke {next.replaceAll('_', ' ')}</button>}<label className="field"><span>Alasan pembatalan</span><textarea value={reason} onChange={e => setReason(e.target.value)} rows={2} /></label><button className="button button-danger" onClick={() => change('DIBATALKAN')}>Batalkan transaksi</button></section>}
    {tx.status === 'DITERIMA' && writable && <section className="panel ops-form"><h2>Ubah catatan dan estimasi</h2><form onSubmit={event => { event.preventDefault(); router.put(`/app/transactions/${tx.id}`, { expected_version: tx.version, catatan_kondisi: condition, estimasi_selesai: estimate, item_clothes: Object.fromEntries(Object.entries(clothes).map(([id, value]) => [id, value === '' ? null : Number(value)])) }, { onError: setErrors }); }}><label className="field"><span>Catatan kondisi (publik)</span><textarea rows={3} value={condition} onChange={e => setCondition(e.target.value)} /></label><label className="field"><span>Estimasi selesai</span><input type="datetime-local" value={estimate} onChange={e => setEstimate(e.target.value)} /></label>{items.map(item => <label className="field" key={item.id}><span>Perkiraan jumlah baju · {item.nama_layanan_snapshot}</span><input type="number" min="0" max="65535" value={clothes[item.id] ?? ''} onChange={event => setClothes(old => ({ ...old, [item.id]: event.target.value }))} /></label>)}<button className="button button-outline">Simpan perubahan</button></form><Link className="button button-outline" href={`/app/transactions/${tx.id}/edit`}>Ubah layanan dan harga</Link></section>}
    <section className="panel"><div className="section-heading"><h2>Riwayat status</h2></div>{history.map((row, index) => <div className="ops-row" key={index}><strong>{row.status.replaceAll('_', ' ')}</strong><span>{row.created_at} WIB</span></div>)}</section>
    <section className="panel"><div className="section-heading"><h2>Riwayat notifikasi</h2></div>{notifications.length === 0 ? <p>Belum ada kiriman.</p> : notifications.map((row, index) => <div className="ops-row" key={index}><strong>{row.kanal === 'whatsapp_manual' ? 'Tautan WA dibuka' : `${row.tipe.replaceAll('_', ' ')} · ${row.kanal}`}</strong><span>{row.tujuan} · {row.status.replaceAll('_', ' ')}{row.reason_code ? ` (${row.reason_code.replaceAll('_', ' ')})` : ''}</span><small>{row.sent_at ?? row.created_at} WIB</small></div>)}</section>
  </AppLayout>;
}
